application: coherent-server-503
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /bootstrap
  static_dir: static/bootstrap

- url: /js
  static_dir: static/js

- url: /.*
  script: ads.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest